# Generated by Django 5.1.2 on 2025-01-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_date_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='Локація', max_length=200, null=True),
        ),
    ]
