# Generated by Django 5.1.2 on 2024-12-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_new_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
