# Generated by Django 5.1.2 on 2024-12-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_new_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='image',
            new_name='file',
        ),
    ]
