# Generated by Django 5.1.2 on 2024-12-18 17:56

import auth_system.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_image_new_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='news_images/', validators=[auth_system.validators.validate_image_size]),
        ),
    ]
