# Generated by Django 5.1.2 on 2024-12-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_new_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='published_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
