# Generated by Django 5.1.2 on 2025-01-02 19:22

import auth_system.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_new_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[auth_system.validators.validate_image_size], verbose_name='media'),
        ),
    ]
