# Generated by Django 5.1.2 on 2024-12-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='users_media/'),
        ),
    ]
