# Generated by Django 5.1.2 on 2024-12-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_user_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='users_media/'),
        ),
    ]
