# Generated by Django 5.1.2 on 2024-12-18 11:30

import auth_system.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_alter_user_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='users_media/', validators=[auth_system.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
