# Generated by Django 5.1.2 on 2025-01-02 19:43

import auth_system.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_alter_user_media_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='media',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[auth_system.validators.validate_image_size], verbose_name='media'),
        ),
    ]
