# Generated by Django 5.1.2 on 2024-12-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_advert_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
