# Generated by Django 5.1.2 on 2024-12-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_alter_advert_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='adverts_media/'),
        ),
    ]
