# Generated by Django 5.1.2 on 2024-12-18 11:42

import adverts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0005_alter_advert_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='adverts_media/', validators=[adverts.validators.validate_image_size]),
        ),
    ]
