# Generated by Django 5.1.2 on 2024-12-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0006_alter_advert_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
