# Generated by Django 5.1.2 on 2024-12-25 16:38

import adverts.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0008_alter_advert_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='media',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[adverts.validators.validate_image_size], verbose_name='media'),
        ),
    ]
