# Generated by Django 5.1.2 on 2024-11-19 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_rename_date_event_event_date'),
        ('institutions', '0003_remove_walk_events_remove_walk_institutions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goat', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progres', 'In progres'), ('completed', 'Completed')], max_length=20)),
                ('events', models.ManyToManyField(to='events.event')),
                ('institution', models.ManyToManyField(to='institutions.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Walk',
                'verbose_name_plural': 'Walk',
                'ordering': ['created_at'],
            },
        ),
    ]
