# Generated by Django 5.1.2 on 2024-11-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_date_event_event_date'),
        ('institutions', '0003_remove_walk_events_remove_walk_institutions_and_more'),
        ('walking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, to='events.event'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='institution',
            field=models.ManyToManyField(blank=True, null=True, to='institutions.institution'),
        ),
    ]
