# Generated by Django 5.1.2 on 2024-11-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walking', '0002_alter_walk_events_alter_walk_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progres', 'In progres'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
    ]
