# Generated by Django 5.1.2 on 2024-12-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walking', '0003_alter_walk_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='number_members',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='walk',
            name='walk_type',
            field=models.CharField(choices=[('nature', 'Nature'), ('city', 'City'), ('historic', 'Historic'), ('sport', 'Sport')], default='nature', help_text='Тип прогулянки', max_length=50),
        ),
    ]
