# Generated by Django 5.1.2 on 2024-12-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walking', '0004_walk_number_members_walk_walk_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walk',
            old_name='walk_type',
            new_name='type',
        ),
    ]
