# Generated by Django 5.1.2 on 2024-12-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walking', '0005_rename_walk_type_walk_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='number_members',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
