# Generated by Django 5.1.2 on 2024-12-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walking', '0006_alter_walk_number_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='name',
            field=models.CharField(default='Прогулянка', max_length=50),
        ),
    ]
