# Generated by Django 5.1.2 on 2024-12-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walking', '0008_alter_walk_goat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='goat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='walk',
            name='type',
            field=models.CharField(choices=[('nature', 'Nature'), ('city', 'City'), ('historic', 'Historic'), ('sport', 'Sport')], default='nature', max_length=50),
        ),
    ]
