# Generated by Django 5.1.2 on 2024-11-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advert',
        ),
    ]
