# Generated by Django 5.1.2 on 2024-11-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_delete_advert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walk',
            name='events',
        ),
        migrations.RemoveField(
            model_name='walk',
            name='institutions',
        ),
        migrations.RemoveField(
            model_name='walk',
            name='user',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Walk',
        ),
    ]
