# Generated by Django 5.1.2 on 2024-12-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_alter_institution_rating_alter_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='ins_media/'),
        ),
    ]
