# Generated by Django 5.1.2 on 2024-12-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_alter_institution_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('Catering', 'Catering'), ('Sport', 'Sport'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Trade', 'Trade'), ('Beauty and health', 'Beauty and health')], max_length=20),
        ),
    ]
