# Generated by Django 5.1.2 on 2024-12-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_alter_review_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-published_at'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
