# Generated by Django 5.1.2 on 2024-12-22 20:41

import institutions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0014_alter_institution_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='media',
            field=models.ImageField(upload_to='ins_media/', validators=[institutions.validators.validate_image_size]),
        ),
    ]
