# Generated by Django 5.1.2 on 2025-01-02 12:01

import cloudinary.models
import institutions.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0015_alter_institution_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='media',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[institutions.validators.validate_image_size], verbose_name='media'),
        ),
    ]
